export default [
  '/import-map.json',

  '/css/main.css',
  '/css/spinner.css',
  '/css/jquery.json-viewer.css',

  '/src/auth/initialize.ts',
  '/src/auth/user.model.ts',

  '/src/components/inventory-editor/fn/is-legal-item-path.ts',
  '/src/components/inventory-editor/inventory-editor.ts',
  '/src/components/inventory-editor/inventory-editor.html',
  '/src/components/inventory-object-viewer/cpp/f-json-types.ts',
  '/src/components/inventory-object-viewer/cpp/inventory-item.ts',
  '/src/components/inventory-object-viewer/cpp/inventory.ts',
  '/src/components/inventory-object-viewer/cpp/sidecar-inventory.ts',
  '/src/components/inventory-object-viewer/inventory-object-viewer.ts',
  '/src/components/inventory-object-viewer/inventory-object-viewer.html',
  '/src/components/meta-editor/meta-editor.ts',
  '/src/components/meta-editor/meta-editor.html',
  '/src/components/page-header/page-header.ts',
  '/src/components/page-header/page-header.html',
  '/src/components/verse-runtime-error-reports/verse-runtime-error-report-modal.ts',
  '/src/components/verse-runtime-error-reports/verse-runtime-error-report-modal.html',
  '/src/components/verse-runtime-error-reports/verse-runtime-error-reports-group-list.ts',
  '/src/components/verse-runtime-error-reports/verse-runtime-error-reports-group-list.html',
  '/src/components/edit-team-domain-modal.ts',
  '/src/components/edit-team-domain-modal.html',
  '/src/components/edit-team-membership-modal.ts',
  '/src/components/edit-team-membership-modal.html',
  '/src/components/edit-team-workspace-modal.ts',
  '/src/components/edit-team-workspace-modal.html',
  '/src/components/new-project-modal.ts',
  '/src/components/new-project-modal.html',
  '/src/components/new-team-modal.ts',
  '/src/components/new-team-modal.html',
  '/src/components/new-module-modal.ts',
  '/src/components/new-module-modal.html',
  '/src/components/view-metadata-modal.ts',
  '/src/components/view-metadata-modal.html',

  '/src/util/async-extender.ts',
  '/src/util/errors.ts',
  '/src/util/ko.ts',
  '/src/util/module-loader.ts',
  '/src/util/template-loader.ts',

  '/src/ux/initialize.ts',
  '/src/ux/keyboard.ts',

  '/src/api.ts',
  '/src/config.ts',
  '/src/index_main.ts',
  '/src/project_main.ts',
  '/src/module_main.ts',
  '/src/team_main.ts',
  '/src/teams_main.ts',
  '/src/inventory_main.ts',
  '/src/helpers.ts',

  '/version',
] as const;
